### ISSUE TITLE
Call I use this library to display all the users and their avatars on my wp site

### ISSUE THREAD

**Issue by showcasefloyd** [Automattic/wpcom.js#108]
I'm trying to see if I can work with this, and the first example I was trying out of the box seems to be given me an error.

<script src="dist/wpcom.js"></script>
<script>
 var wpcom = WPCOM();
  var blog = wpcom.site('myblow.wordpress.com');

  console.log(blog);

  blog.posts({ number: 8 },function(err, list) {

		console.log(list);
  });
</script>

Any help would be appreciated

**Comment by retrofox** [comment]
what error did you get ?

**Comment by showcasefloyd** [comment]
Uncaught TypeError: blog.posts is not a function

**Comment by retrofox** [comment]
I guess you aren't creating rightly the `blog` instance.

```js
var blog = wpcom.site('en.blog.wordpress.com');
blog.posts(function(err, data) {
  // data posts list object
});
```

**Comment by showcasefloyd** [comment]
Nope. Same error.

It's telling me it's an (anonymous function) call which it is. 

Okay dumb question. I'm running this in my browser as an html and just pulling it the wpcom.js file.

Would it be better if I just run this as a javascript file using node.js?

**Comment by retrofox** [comment]
https://github.com/Automattic/wpcom.js#browser

**Comment by showcasefloyd** [comment]
Okay, yeah so this is what I was trying to do. In fact I believe that is where I pulled my example code from, but even with your example I get the same error.

Okay, thanks anyway.

**Comment by retrofox** [comment]
I'm sorry @showcasefloyd. I've been a bit grosser with you.
It's the same. I mean run wpcom.js in a browser or in node.js.

You can see a real example running in http://automattic.github.io/wpcom.js. Open dev console and you'll see the gotten posts. :-D
