### ISSUE TITLE
`describe.only` prevents full test suite from running

### ISSUE THREAD

**Issue by aduth** [Automattic/wpcom.js#121]
The addition of [`describe.only` in `test.wpcom.promises.js`](https://github.com/Automattic/wpcom.js/blob/2f64317fe28a95f70221a7c82cf293d71729f467/test/test.wpcom.promises.js#L29) appears to prevent the full test suite from running. When using either `make test-all` or `make test wpcom.site.media`, the only tests run are those within the `wpcom.promises` descriptor block. By removing `.only`, the desired tests run as expected.

@dmsnell, is the `only` required in this case?

**Comment by dmsnell** [comment]
Oh dear. Good catch!
