### ISSUE TITLE
Cannot `npm install wpcom`

### ISSUE THREAD

**Issue by nylen** [Automattic/wpcom.js#124]
```sh
$ npm install --save wpcom
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
|
> wpcom@4.7.2 postinstall /Users/james/code/wpcom/new-sites/node_modules/wpcom
> make babelify

module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/james/code/wpcom/new-sites/node_modules/wpcom/node_modules/.bin/babel'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
make: *** [babelify] Error 1
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save" "wpcom"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! wpcom@4.7.2 postinstall: `make babelify`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the wpcom@4.7.2 postinstall script 'make babelify'.
npm ERR! This is most likely a problem with the wpcom package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make babelify
npm ERR! You can get their info via:
npm ERR!     npm owner ls wpcom
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/james/code/wpcom/new-sites/npm-debug.log
```

:disappointed:

**Comment by nylen** [comment]
```sh
$ npm install --save wpcom@4.7.2
[fails]
$ npm install --save wpcom@4.7.1
[succeeds]
```

Version 4.7.2 does not appear to exist on GitHub:
- https://github.com/Automattic/wpcom.js/tree/4.7.2 [404 Not Found]
- https://github.com/Automattic/wpcom.js/tree/4.7.1 [200 OK]

**Comment by retrofox** [comment]
@nylen working in a new release to fix this bug. It's related with the new compiling system. I've removed `@4.7.2` from npm. Thanks for the report.

**Comment by mdawaffe** [comment]
I just ran into this too with `@4.8.0`.

> It's related with the new compiling system

This comment: https://github.com/npm/npm/issues/10095#issuecomment-155938351 (and the surrounding issue) combined with our [Makefile's use of the module's `/.bin/` directory](https://github.com/Automattic/wpcom.js/blob/6ccef84eec36d757ffcd53e8afdf96b2af931bba/Makefile#L6) I think describes the problem.

**Comment by retrofox** [comment]
I've run `npm install --save wpcom` in a new folder and It works. https://cloudup.com/c-la8IVRSIP
Maybe it's related with npm version ?

**Comment by retrofox** [comment]
yup. npm version.
So to fix that we can do:

1) a new release to work in npm@3.x fixing the bin file path
2) require `babel` installed in the system: `npm install -g babel`
3) remove `postinstall` script from the package.json file and start to control the babelified files into dist/ folder

I think the better is the third option because it's less intrusive and simplest.
