### ISSUE TITLE
Something wrong w/ highlight.js styles on site

### ISSUE THREAD

**Issue by nemoDreamer** [Automattic/wpcom.js#128]
Hey folks,
something's wrong w/ you code example. It's getting a dark background that's making it illegible... :cry: 

<img width="273" alt="wpcom_js_-_official_javascript_library_for_the_wordpress_com_rest_api" src="https://cloud.githubusercontent.com/assets/9303/11350923/edc38eb8-9201-11e5-9389-9b65c87cb2db.png">

**Comment by retrofox** [comment]
partially fixed. Thanks @nemoDreamer !!

![image](https://cloud.githubusercontent.com/assets/77539/11353717/698f1194-9224-11e5-98f1-60c5f33d684b.png)

**Comment by nemoDreamer** [comment]
noice.
