### ISSUE TITLE
Question regarding use without using Wordpress.com as host

### ISSUE THREAD

**Issue by j** [Automattic/wpcom.js#143]
Is there a way to use this client without using wordpress.com as a host?  Do we just need to install Jetpack and it should all work?  Sorry for a lazy issue, but I don't have time to test at the moment and are spec'ing out a new project and this came about.

**Comment by retrofox** [comment]
you just need add jetpack to your self hosted WordPress installation. With that you can connect wpcom.js with your blog (using WordPress.com like a proxy)

**Comment by datesss** [comment]
as far as i can tell, its not possible to connect jetpack to wordpress.com or enable the json api when developing locally... is that correct?
