### ISSUE TITLE
Error on wpcom module import

### ISSUE THREAD

**Issue by rspt** [Automattic/wpcom.js#172]
Hello,

I ran over an issue when trying to import the wpcom as a module. When I type this:

```
const wpcom = require('wpcom')()
```

the browser raise this error: 
```
TypeError: list.forEach is not a function. (In 'list.forEach', 'list.forEach' is undefined)
```

---

For information, I've tested it on Chrome & Safari and I use Webpack, ES6 & Babel for my projects.

**Comment by retrofox** [comment]
I'm not completely aware how is configured your app but It seems work fine in our [web app](www.wpcomjs.com). Maybe you could take a look to [this one](https://github.com/Automattic/wpcom.js/tree/master/webapp).

**Comment by janjarfalk** [comment]
I've just got the same problem. Manifests in this boilerplate https://github.com/janjarfalk/babel6-wpcom-react-redux-cssmodules

**Comment by janjarfalk** [comment]
```json
// wpcom.js/lib/runtime/site.post.get.json
[
	{ "name": "likesList", "subpath": "likes" },
	{ "name": "subscribersList", "subpath": "subscribers" }
]
```

```js
// wpcom/dist/lib/site.post.js
var _runtimeSitePostGetJson = require('./runtime/site.post.get.json');
console.log(_runtimeSitePostGetJson) // Logs an empty object, {}
```

**Comment by rspt** [comment]
I've pushed my code here: https://github.com/rspt/cuae-client

Just run `npm install && npm start` and open the server. The error must appear.

**Comment by retrofox** [comment]
we've left to use json files to define the runtime methods. Now the methods are defined like a module using js extensiones. https://github.com/Automattic/wpcom.js/pull/192
