### ISSUE TITLE
Cannot resolve module fs

### ISSUE THREAD

**Issue by rspt** [Automattic/wpcom.js#173]
Hello!

I ran into this error just after installing the wpcom lib (via npm) and trying to bundle it using webpack:

```
ERROR in ./~/wpcom/dist/lib/site.media.js
Module not found: Error: Cannot resolve module 'fs' in /Users/xxx/client/node_modules/wpcom/dist/lib
 @ ./~/wpcom/dist/lib/site.media.js 4:9-22
```

Note this error disappear if I install the `fs`module via npm

**Comment by retrofox** [comment]
Here is an [webpack issue](https://github.com/webpack/jade-loader/issues/8) talking about. You could add `"browser": { "fs": false }` to solve it.
https://github.com/Automattic/wpcom.js/blob/master/webpack.config.js#L4-L6

**Comment by oskosk** [comment]
I can assert that adding this to my project's main `webpack.config.js` did the trick
```
  node: {
    fs: 'empty'
  },
```

**Comment by rspt** [comment]
Yes thanks a lot for the answer. It still seems to me a little bit odd to add something in my config or to install a package to make one works!
