### ISSUE TITLE
post.author object

### ISSUE THREAD

**Issue by johandavidsen** [Automattic/wpcom.js#175]
I noticed that when I use the WPCOM to read post from a Wordpress blog, the post.author object contains a property: login.

Is this the login name that the user uses to login to his blog? and if it is, is it smart to distribute that to anyone?

**Comment by retrofox** [comment]
yes, I'm afraid that it's the login username of the author. We have to keep in mind that wpcom.js is justa a abstraction layer used to connect with the REST-API. Here there is the doc page: https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/posts/%24post_ID/
I'll dive a little on this.

**Comment by nylen** [comment]
Worth noting that we're not exposing any information here which isn't already publicly available.  Example:

- https://jnylen0.wordpress.com/2015/11/05/542/
- "James Nylen" link points to https://jnylen0.wordpress.com/author/jnylen0/ (note author username in URL)

**Comment by retrofox** [comment]
let's close this one @johandavidsen
