### ISSUE TITLE
Ditch babel5 dependency

### ISSUE THREAD

**Issue by blowery** [Automattic/wpcom.js#200]
Pulling a hard dependency on babel 5 is unnecessary. Consider switching to [es6-promise](https://github.com/stefanpenner/es6-promise) which doesn't have as much baggage for downstream projects.

**Comment by TooTallNate** [comment]
@blowery  [`babel-runtime` is used in other places](https://github.com/Automattic/wpcom.js/blob/86f100fcad951096ac422918a2528e9c40634cfb/dist/lib/site.wordads.js#L1) as well unfortunately, so it's not just Promise.

I'm thinking that upgrading to Babel 6 and a major version bump for wpcom.js might be good enough to satisfy #1515. Yay or nay?

**Comment by TooTallNate** [comment]
Note that I'm also planning on removing `babel` as a dependency in general. It should be a dev dependency and not installed when being consumed by a parent module.

`babel-runtime` as a dep I don't really see any way of removing, short of refactoring all the code to not use ES6 anymore, but I don't think that's the direction we want to go in.

**Comment by TooTallNate** [comment]
Fixed by #201.
