### ISSUE TITLE
Renew expired HTTPS certificate

### ISSUE THREAD

**Issue by sagirk** [Automattic/wpcom.js#219]
When I go to [`https://wpcomjs.com`](https://wpcomjs.com), Chrome shows the below warning:

![image](https://user-images.githubusercontent.com/2608321/41034837-7dfccbf4-69a8-11e8-935b-7aae1fae233f.png)

Looks like it expired only recently (23/MAY/2018):

![image](https://user-images.githubusercontent.com/2608321/41034895-a9a82334-69a8-11e8-8dd0-512552dd1913.png)

Whoever is in charge of this, can you please renew the certificate (its letsencrypt... wouldn't it be a good idea to [automate](https://community.letsencrypt.org/t/how-to-automatically-renew-certificates/4393) the [renewals](https://certbot.eff.org/docs/using.html#renewing-certificates))?

**Comment by bazza** [comment]
> Whoever is in charge of this, can you please renew the certificate (its letsencrypt... wouldn't it be a good idea to automate the renewals)?

I guess somewhat ironically, this site is hosted on Github (using pages) and the cert expired for some reason.  Will try to contact them to see why :)

**Comment by bazza** [comment]
Github support said it was a bug on their side. While they work on fixing it they have "manually" renewed the cert.  Going to close this issue - thanks for the report!
