### ISSUE TITLE
send-request throws error if no query/body supplied for POST

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wpcom.js#85]
Due to the check currently on line 44

`if (query.apiVersion) {`

in `lib/util/send-request.js`, this library can sometimes throw an error. If `null` is passed as the query (body) to a POST request for example, then this line throws an error:

`Uncaught TypeError: Cannot read property 'apiVersion' of null`

We probably want to confirm `query` in addition to `query.apiVersion` here.

**Comment by beaulebens** [comment]
Temporary fix is to pass `{}` as the body instead of `null`, but we should handle this at the `wpcom.js` level to avoid people running up against it at all ideally.

**Comment by retrofox** [comment]
@beaulebens I've added a request lib to make requests arbitrarily.  What kind of request are you trying to do.

**Comment by retrofox** [comment]
@beaulebens fixed.
