### ISSUE TITLE
Add Support for Stand Alone sites

### ISSUE THREAD

**Issue by OJayRobinson** [Automattic/wpcom.js#97]
Add support for stand alone sites.

in request, the url is built with the assumption
var url = proxyOrigin + '/rest/v' + apiVersion + params.path;

This prevents using wpcom.js on standalone sites without hacking.

**Comment by timmyc** [comment]
@OJayRobinson could you give a code example where this pattern isn't working out for you?  Also by stand-alone site are you referring to a WordPress.org install with Jetpack and the JSON API enabled?

**Comment by OJayRobinson** [comment]
yeah sorry for not being more clear, I do mean a self hosted WordPress.org install with JSON API enabled.  I want to send the requests to the stand alone site, but they are directed to the proxyOrigin.

When I hacked out the proxyOrigin, '/site/', and other related code it works but it is an ugly hack job.

This is the code I was trying to run:
``` javascript
	  var wpcom = WPCOM();
	  wpcom
	    .site('http://www.siteaddress.com/wp-json')
	    .postsList({ number: 5 }, function(err, data) {
	      if (err) throw err;
		 posts = data;
		 console.log("posts ", posts);
	    });
```

Maybe there is another way to do this that I don't know about?

**Comment by retrofox** [comment]
@OJayRobinson it isn't easy to do but I think we could start to work to support WP-API. Anyway you could use these libraries:

client -> https://github.com/WP-API/client-js
nodejs -> https://github.com/kadamwhite/wordpress-rest-api

Thanks!

**Comment by OJayRobinson** [comment]
@retrofox cool thanks for the references
